adoption-site/myproject/models.py
from myproject import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class Puppy(db.Model):
    """
    Class representing a record in table "puppies".
    """
    __tablename__ = "puppies"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(250), nullable=False)
    owner = db.relationship("Owner", backref="puppy",
                            uselist=False)  # one-to-one

    def __init__(self, name: str):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name is {self.name} and owner name is {self.owner.name}."
        else:
            return f"Puppy name is {self.name} and is not assigned an owner yet."


class Owner(db.Model):
    """
    Class representing a record in table "owners".
    """
    __tablename__ = "owners"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(250), nullable=False)
    puppy_id = db.Column(db.Integer, db.ForeignKey("puppies.id"))

    def __init__(self, name: str, puppy_id: int):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return f"Owner {self.name}"


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(db.Model, UserMixin):
    """
    Class representing a record in table "users".
    """
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True, index=True, nullable=False)
    username = db.Column(db.String(100), unique=True, index=True,
                         nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    def __init__(self, email: str, username: str, password: str):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password=password,
                                                    method="pbkdf2:sha256",
                                                    salt_length=8)

    def check_password(self, password: str):
        return check_password_hash(pwhash=self.password_hash,
                                   password=password)

adoption-site/myproject/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length, InputRequired
from wtforms.validators import ValidationError
from myproject.models import User


class RegistrationForm(FlaskForm):
    """
    Form for registering a user.
    """
    username = StringField(label="Username", validators=[
        DataRequired()])
    email = StringField(label="Email", validators=[DataRequired(), Email()])
    password = PasswordField(label="Password", validators=[InputRequired(),
                                                           Length(min=8),
                                                           EqualTo(
                                                               fieldname="confirm_password",
                                                               message="Passwords must match.")])
    confirm_password = PasswordField(label="Confirm Password",
                                     validators=[DataRequired()])
    submit = SubmitField(label="Register")

    def validate_email(self, email):
        if User.query.filter_by(email=self.email.data).first():
            raise ValidationError("Email has been already registered.")

    def validate_username(self, username):
        if User.query.filter_by(username=self.username.data).first():
            raise ValidationError("Username has already been registered.")


class LoginForm(FlaskForm):
    """
    Form for loging user.
    """
    email = StringField(label="Email", validators=[DataRequired(), Email()])
    password = PasswordField(label="Password", validators=[DataRequired()])
    submit = SubmitField(label="Login")

adoption-site/myproject/owners/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired


class AddForm(FlaskForm):
    """
    Form for adding an owner.
    """
    name = StringField(label="Name of the owner", validators=[
        DataRequired(message="Please enter the name of the owner.")])
    puppy_id = IntegerField(label="ID of the puppy", validators=[
        DataRequired(message="Please enter the ID of the puppy.")])
    submit = SubmitField(label="Add owner")

adoption-site/myproject/puppies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired


class AddForm(FlaskForm):
    """
    Form for creating a puppy.
    """
    name = StringField(label="Puppy name", validators=[
        DataRequired(message="Please enter the name of the puppy.")])
    submit = SubmitField(label="Add puppy")


class DeleteForm(FlaskForm):
    """
    Form for deleting a puppy.
    """
    id = IntegerField(label="ID number of puppy", validators=[DataRequired(
        message="Please enter the id of the puppy to be removed.")])
    submit = SubmitField(label="Remove puppy")

adoption-site/myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

basedir = os.path.abspath(os.path.dirname(__file__))

app = Flask(__name__)
# os.urandom(16)
app.config["SECRET_KEY"] = b'\x95\xac$*\x9a\xa0{\xdd\xa8\x16\xeb(\x15\x10\xabB'
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///" + os.path.join(basedir,
                                                                    "data.sqlite")
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db = SQLAlchemy(app)
Migrate(app, db)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "login"

from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(puppies_blueprint, url_prefix="/puppies")
app.register_blueprint(owners_blueprint, url_prefix="/owners")

adoption-site/myproject/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owners.forms import AddForm
from flask_login import login_required

owners_blueprint = Blueprint("owners", __name__,
                             template_folder="templates/owners")


@owners_blueprint.route("/add", methods=["GET", "POST"])
@login_required
def add():
    form = AddForm()

    if form.validate_on_submit():
        owner_name = form.name.data
        puppy_id = form.puppy_id.data
        owner = Owner(name=owner_name, puppy_id=puppy_id)
        db.session.add(owner)
        db.session.commit()

        return redirect(url_for("puppies.list"))

    return render_template("add_owner.html", form=form)

adoption-site/myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DeleteForm
from flask_login import login_required

puppies_blueprint = Blueprint("puppies", __name__,
                              template_folder="templates/puppies")


@puppies_blueprint.route("/add", methods=["GET", "POST"])
@login_required
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        new_puppy = Puppy(name=name)
        db.session.add(new_puppy)
        db.session.commit()

        return redirect(url_for("puppies.list"))

    return render_template("add.html", form=form)


@puppies_blueprint.route("/list")
def list():
    puppies = Puppy.query.all()

    return render_template("list.html", puppies=puppies)


@puppies_blueprint.route("/delete", methods=["GET", "POST"])
@login_required
def delete():
    form = DeleteForm()

    if form.validate_on_submit():
        id = form.id.data
        puppy = Puppy.query.get(id)
        db.session.delete(puppy)
        db.session.commit()

        return redirect(url_for("puppies.list"))

    return render_template("delete.html", form=form)

adoption-site/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Puppy Adoption</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/bootstrap.min.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('index') }}">Puppy Adoption</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('puppies.add') }}">Add Puppy</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('puppies.delete') }}">Delete Puppy</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('owners.add') }}">Add Owner</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('puppies.list') }}">List Puppies</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('login') }}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('register') }}">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% for message in get_flashed_messages() %}
<div class="alert alert-primary alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="container-fluid">
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='scripts/jquery.slim.min.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/bootstrap.min.js') }}"></script>
</body>
</html>

adoption-site/myproject/templates/index.html
{% extends "base.html" %}

{% block content %}

{% if current_user.is_authenticated %}
<h1>Welcome, {{ current_user.username }}</h1>
{% else %}
<p>Please login or register</p>
{% endif %}

{% endblock %}

adoption-site/myproject/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form method="POST" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email(class_="form-control") }}
        {% if form.email.errors %}
        {% for error in form.email.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password(class_="form-control") }}
        {% if form.password.errors %}
        {% for error in form.password.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {{ form.submit(class_="btn btn-primary") }}
</form>
{% endblock %}

adoption-site/myproject/templates/register.html
{% extends "base.html" %}

{% block content %}
<h1>Registration</h1>
<form method="POST" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}
        {{ form.username(class_="form-control") }}
        {% if form.username.errors %}
        {% for error in form.username.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email(class_="form-control") }}
        {% if form.email.errors %}
        {% for error in form.email.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password(class_="form-control") }}
        {% if form.password.errors %}
        {% for error in form.password.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.confirm_password.label }}
        {{ form.confirm_password(class_="form-control") }}
        {% if form.confirm_password.errors %}
        {% for error in form.confirm_password.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    {{ form.submit(class_="btn btn-primary") }}
</form>
{% endblock %}