company-blog/project/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):
    """
    Form for submitting a blog post.
    """
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Body", validators=[DataRequired()])
    submit = SubmitField("Submit")

company-blog/project/blog_posts/views.py
from flask import Blueprint, render_template, url_for, flash, redirect, \
    request, abort
from flask_login import login_user, current_user, logout_user, login_required
from project import db
from project.models import BlogPost
from project.blog_posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)


@blog_posts.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        blog = BlogPost(title=title, content=content, user_id=current_user.id)
        db.session.add(blog)
        db.session.commit()
        flash("Blog Post created.", category="success")

        return redirect(url_for("core.index"))

    return render_template("create_post.html", form=form)


@blog_posts.route("/<int:blog_post_id>")
def read_blog_post(blog_post_id: int):
    post = BlogPost.query.get_or_404(blog_post_id)

    return render_template("blog_post.html", post=post)


@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(blog_post_id: int):
    post = BlogPost.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Blog Post Updated.", category="success")

        return redirect(
            url_for("blog_posts.read_blog_post", blog_post_id=post.id))

    form.title.data = post.title
    form.content.data = post.content

    return render_template("create_post.html", title="Update Blog Post",
                           form=form)


@blog_posts.route("/<int:blog_post_id>/delete", methods=["POST"])
@login_required
def delete_post(blog_post_id: int):
    post = BlogPost.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash("Blog Post Removed.", category="success")

    return redirect(url_for("core.index"))

company-blog/project/core/views.py
from flask import render_template, Blueprint, request
from project.models import BlogPost

core = Blueprint("core", __name__)


@core.route("/")
def index():
    page = request.args.get("page", 1, type=int)
    posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,
                                                                   per_page=5)
    return render_template("index.html", posts=posts)


@core.route("/about")
def about():
    return render_template("about.html")

company-blog/project/users/views.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from project import db
from project.models import User, BlogPost
from project.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from project.users.picture_handler import add_profile_pic

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data
        )

        db.session.add(user)
        db.session.commit()
        flash("Thank you for your registration.", category="success")

        return redirect(url_for("users.login"))

    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()

        if user and user.check_password(password):
            login_user(user)

            next = request.args.get("next")

            if next == None or next[0] != "/":
                return redirect(url_for("core.index"))

            return redirect(next)
        else:
            flash("Invalid credentials.", category="danger")

    return render_template("login.html", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()

    return redirect(url_for("core.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateUserForm()

    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        db.session.commit()
        flash("User profile updated successfully.", category="success")

        return redirect(url_for("users.account"))

    form.username.data = current_user.username
    form.email.data = current_user.email
    profile_image = url_for("static",
                            filename="profile_pics/" + current_user.profile_image)

    return render_template("account.html", profile_image=profile_image,
                           form=form)


@users.route("/<username>")
def user_posts(username: str):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(BlogPost.date.desc()).paginate(page=page,
                                                               per_page=5)
    # posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template("user_blog_posts.html", posts=posts, user=user)

company-blog/project/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">About Company Blog!</h1>
    <p class="lead">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
        standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make
        a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
        remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
        Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions
        of Lorem Ipsum.
    </p>
</div>
{% endblock %}

company-blog/project/templates/account.html
{% extends "base.html" %}

{% block content %}
<h1>User's Profile</h1>

<div class="text-center">
    <img src="{{ profile_image }}" alt="{{ current_user.username }} profile picture">
    <h2>{{ current_user.username }}</h2>
</div>

<form method="POST" action="" enctype="multipart/form-data" novalidate>
    {{ form.hidden_tag() }}

    {% for field in form %}
    {% if "submit" != field.name and "csrf_token" != field.name %}
    <div class="form-group">
        {{ field.label }}
        {{ field(class_="form-control") }}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endfor %}

    {{ form.submit(class_="btn btn-primary") }}
</form>
{% endblock %}

company-blog/project/templates/base.html
<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Jack Lee">
    <meta name="description" content="An example blog with Flask">
    <title>Company Blog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vendor/bootstrap.min.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('core.index') }}">Company Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('core.index') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('core.about') }}">About</a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('blog_posts.create_post') }}">Create Post</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% for category, message in get_flashed_messages(with_categories=true) %}
<div class="alert alert-{{ 'primary' if 'message' == category else category }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}

<div class="container-fluid">
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='scripts/vendor/jquery.slim.min.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/vendor/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/vendor/popper.min.js') }}"></script>
{{ moment.include_moment(local_js=url_for("static", filename="scripts/vendor/moment-with-locales.min.js")) }}
{{ moment.locale("pt-BR") }}
</body>
</html>

company-blog/project/templates/blog_post.html
{% extends "base.html" %}

{% block content %}

<h1>
    {{ post.title }}
</h1>
<h2 class="text-muted">Written by {{ post.author.username }}</h2>
<h3 class="text-muted">Published on {{ moment(post.date).format("LLL") }}</h3>

<p>
    {{ post.content }}
</p>

{% if post.author == current_user %}
<div>
    <a title="Update post" class="btn btn-primary" href="{{ url_for('blog_posts.update_post', blog_post_id=post.id) }}">Update</a>
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
</div>
{% endif %}

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Blog Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

company-blog/project/templates/create_post.html
{% extends "base.html" %}

{% block content %}

<h1>
    {{ title or "Create Blog Post" }}
</h1>

<form method="POST" novalidate>
    {{ form.hidden_tag() }}

    {% for field in form %}
    {% if "submit" != field.name and "csrf_token" != field.name %}
    <div class="form-group">
        {{ field.label }}
        {{ field(class_="form-control") }}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endfor %}

    {{ form.submit(class_="btn btn-primary") }}
</form>

{% endblock %}

company-blog/project/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="display-4">Welcome to Company Blog!</h1>

{% for post in posts.items %}
<div class="card">
    <div class="card-body">
        <h2 class="card-title">
            <a title="{{ post.title }}" href="{{ url_for('blog_posts.read_blog_post', blog_post_id=post.id) }}">{{
                post.title
                }}</a>
        </h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written by {{ post.author.username
            }}</a>
        <p class="text-muted">Published on {{ moment(post.date).format("LLL") }}</p>
        <a href="{{ url_for('blog_posts.read_blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog
            Post</a>
    </div>
</div>
{% endfor %}

{% if posts.items %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if posts.page == page_num %}
        <li class="page-item disabled"><a class="page-link"
                                          href="{{ url_for('core.index', page=page_num) }}">{{
            page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link"
                                 href="{{ url_for('core.index', page=page_num) }}">{{
            page_num }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endif %}

{% endblock %}

company-blog/project/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>

<form method="POST" novalidate>
    {{ form.hidden_tag() }}

    {% for field in form %}
    {% if "submit" != field.name and "csrf_token" != field.name %}
    <div class="form-group">
        {{ field.label }}
        {{ field(class_="form-control") }}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endfor %}

    {{ form.submit(class_="btn btn-primary") }}
</form>

{% endblock %}

company-blog/project/templates/register.html
{% extends "base.html" %}

{% block content %}
<h1>Registration</h1>

<form method="POST" novalidate>
    {{ form.hidden_tag() }}

    {% for field in form %}
    {% if "submit" != field.name and "csrf_token" != field.name %}
    <div class="form-group">
        {{ field.label }}
        {{ field(class_="form-control") }}
        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    {% endfor %}

    {{ form.submit(class_="btn btn-primary") }}
</form>
{% endblock %}

company-blog/project/templates/user_blog_posts.html
{% extends "base.html" %}

{% block content %}

<div class="text-center">
    <img src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}"
         alt="{{ user.username }} profile picture">
    <h1>Welcome to the page for {{ user.username }}</h1>
</div>

{% for post in posts.items %}
<h2>
    <a href="{{ url_for('blog_posts.read_blog_post', blog_post_id=post.id) }}">{{ post.title }}</a>
</h2>
<p>
    Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username
    }}</a>
</p>
<p class="text-muted">
    Published on {{ moment(post.date).format("LLL") }}
</p>
<p>
    {{ post.text }}
</p>
{% endfor %}

{% if posts.items %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if posts.page == page_num %}
        <li class="page-item disabled"><a class="page-link"
                                          href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
            page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link"
                                          href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{
            page_num }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</nav>
{% endif %}

{% endblock %}